export const SITE = {
  name: 'Comercyo.com',
  domain: 'https://comercyo.com',
  base: '/',
  lang: 'es',
  locale: 'es-CO',
  defaultTitle: 'Desarrollo de Software Personalizado para Tu Negocio',
  description:
    'Especializados en E-commerce, ERPs, CRMs y Automatización. Transformamos tus procesos empresariales con soluciones tecnológicas a medida, potenciando productividad y crecimiento.',
  keywords: [
    // Desarrollo de Software
    'Desarrollo de Software Personalizado',
    'Desarrollo de Software a Medida',
    'Creación de Software',
    'Software Personalizado',
    'Desarrollo de Aplicaciones',
    'Desarrollo de Sistemas',
    'Programación de Software',
    'Desarrollo Web',
    'Desarrollo de Aplicaciones Web',
    'Desarrollo de Aplicaciones Móviles',
    
    // E-commerce y Tiendas Online
    'E-commerce',
    'Ecommerce',
    'Tienda Virtual',
    'Tiendas Virtuales',
    'Tienda Online',
    'Tiendas Online',
    'Comercio Electrónico',
    'Plataforma de Ventas Online',
    'Página de Ventas',
    'Catálogo Digital',
    'Marketplace',
    'Carrito de Compras',
    'Pasarela de Pagos',
    'Tienda en Línea',
    
    // Sistemas Empresariales
    'ERP',
    'Sistema ERP',
    'Sistemas ERP',
    'CRM',
    'Sistema CRM',
    'Sistemas CRM',
    'Sistema de Gestión',
    'Sistemas de Gestión Empresarial',
    'Software de Gestión',
    'Sistema de Inventarios',
    'Control de Inventarios',
    'Gestión de Inventarios',
    
    // Sistemas Contables y Financieros
    'Sistema Contable',
    'Sistemas Contables',
    'Software Contable',
    'Contabilidad Digital',
    'Sistema de Facturación',
    'Facturación Electrónica',
    'Software de Facturación',
    'Sistema de Nómina',
    'Software de Nómina',
    'Control Financiero',
    'Gestión Financiera',
    
    // Automatización
    'Automatización',
    'Automatización de Procesos',
    'Automatización Empresarial',
    'Automatización de Negocios',
    'Procesos Automatizados',
    'Workflows Automatizados',
    'Integración de Sistemas',
    'API',
    'Integración API',
    
    // Soluciones Específicas
    'Sistema de Punto de Venta',
    'POS',
    'Software POS',
    'Sistema de Reservas',
    'Sistema de Citas',
    'Sistema de Turnos',
    'Portal Web',
    'Página Web Corporativa',
    'Sitio Web Empresarial',
    'Landing Page',
    'Intranet',
    'Extranet',
    
    // Servicios y Consultoría
    'Consultoría de Software',
    'Transformación Digital',
    'Digitalización de Empresas',
    'Soluciones Tecnológicas',
    'Soluciones de Software',
    'Desarrollo a la Medida',
    'Software para Empresas',
    'Software Empresarial',
    'Tecnología para Negocios',
    
    // Industrias y Sectores
    'Software para Retail',
    'Software para Restaurantes',
    'Software para Hoteles',
    'Software para Clínicas',
    'Software para Consultorio',
    'Software para Gimnasios',
    'Software para Educación',
    'Software para Logística',
    'Software para Manufactura',
    'Software para Distribución',
    
    // Términos Técnicos
    'Base de Datos',
    'Cloud Computing',
    'Software en la Nube',
    'SaaS',
    'Aplicación Web',
    'Dashboard',
    'Panel de Control',
    'Reportes Automáticos',
    'Business Intelligence',
    'BI',
    
    // Localización
    'Desarrollo de Software en Colombia',
    'Software Colombia',
    'Empresa de Software',
    'Comercyo'
  ],
  author: {
    name: 'Comercyo.com',
    email: 'comercyodev@gmail.com'
  },
  social: {
    facebook: 'https://www.facebook.com/comercyocom/',
  },
  // Ciudades objetivo para schema/SEO local
  cities: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
    'Ibagué',
    'Pasto',
    'Manizales',
    'Neiva',
    'Villavicencio',
    'Armenia',
    'Valledupar',
    'Montería',
    'Sincelejo',
    'Popayán',
    'Tunja',
    'Florencia',
    'Riohacha',
    'Quibdó',
    'Yopal',
    'Leticia',
    'Soacha',
    'Palmira',
    'Bello',
    'Itagüí',
    'Envigado',
    'Soledad',
    'Dosquebradas',
    'Barrancabermeja',
    'Floridablanca',
    'Girón',
    'Tuluá',
    'Buga',
    'Maicao',
    'Apartadó',
    'Turbo',
    'Sogamoso',
    'Duitama',
    'Facatativá',
    'Zipaquirá',
    'Chía',
    'Fusagasugá',
    'Girardot',
    'Rionegro',
    'Cartago',
    'Piedecuesta',
    'Malambo',
    'Ciénaga',
    'Magangué',
    'Lorica',
    'Caucasia',
    'Ocaña',
    'Pamplona',
    'Ipiales',
    'Tumaco',
    'Espinal',
    'Melgar',
    'Acacías',
    'Granada',
    'Arauca',
    'Mocoa',
    'San Andrés',
    'Providencia',
    'Puerto Carreño',
    'Inírida',
    'Mitú',
    'Cartago',
    'Sabaneta',
    'La Estrella',
    'Caldas',
    'Copacabana',
    'Barbosa',
    'Marinilla',
    'El Carmen de Viboral',
    'La Ceja',
    'Yarumal',
    'Andes',
    'Santa Rosa de Cabal',
    'La Virginia',
    'Chinchiná',
    'Cajicá',
    'Mosquera',
    'Madrid',
    'Funza',
    'Cota',
    'Tocancipá',
    'Tenjo',
    'Tabio',
    'La Calera',
    'Sopó',
    'Gachancipá',
    'Guatavita',
    'Arbeláez',
    'Silvania',
    'San Antonio del Tequendama',
    'Ricaurte',
    'Anapoima',
    'Jamundí',
    'Yumbo',
    'Candelaria',
    'Florida',
    'Pradera',
    'Santander de Quilichao',
    'Puerto Tejada',
    'Corinto',
    'Caloto',
    'Villa Rica',
    'Sevilla',
    'Zarzal',
    'Roldanillo',
    'La Unión',
    'Andalucía',
    'Toro',
    'Obando',
    'Bolívar',
    'El Cerrito',
    'Guacarí',
    'Ginebra',
    'Dagua',
    'Buenaventura',
    'Quibdó',
    'Istmina',
    'Condoto',
    'Tadó',
    'Bahía Solano',
    'Nuquí',
    'Riosucio',
    'Supía',
    'Anserma',
    'Viterbo',
    'Neira',
    'Salamina',
    'Aguadas',
    'Pácora',
    'Aranzazu',
    'Marmato',
    'Marsella',
    'Santa Rosa de Osos',
    'Entrerríos',
    'San Pedro de los Milagros',
    'Don Matías',
    'Belmira',
    'San José de la Montaña',
    'Angostura',
    'Briceño',
    'Valdivia',
    'Tarazá',
    'Cáceres',
    'El Bagre',
    'Zaragoza',
    'Segovia',
    'Remedios',
    'Yondó',
    'Puerto Berrío',
    'Puerto Nare',
    'Puerto Triunfo',
    'San Luis',
    'San Carlos',
    'San Rafael',
    'Granada',
    'Cocorná',
    'San Francisco',
    'Sonsón',
    'Abejorral',
    'Argelia',
    'Nariño',
    'Venecia',
    'Fredonia',
    'Amagá',
    'Titiribí',
    'Heliconia',
    'Angelópolis',
    'Salgar',
    'Támesis',
    'Jericó',
    'Pueblorrico',
    'Tarso',
    'Betania',
    'Hispania',
    'Ciudad Bolívar',
    'Urrao',
    'Frontino',
    'Abriaquí',
    'Dabeiba',
    'Uramita',
    'Cañasgordas',
    'Peque',
    'Sabanalarga',
    'Liborina',
    'Olaya',
    'Sopetrán',
    'San Jerónimo',
    'Ebéjico',
    'Santa Fe de Antioquia',
    'Buriticá',
    'Giraldo',
    'Toledo',
    'Caicedo',
    'Santafé de Antioquia'
  ],
  defaultImage: '/images/og-image.jpg'
};
